services:
  trt-builder:
    image: nvcr.io/nvidia/tritonserver:26.05-py3  
    command:
      - /usr/src/tensorrt/bin/trtexec
      - --onnx=/models/detect_blood/1/model.onnx
      - --saveEngine=/models/detect_blood_trt/1/model.plan
      - --fp16
      - --minShapes=images:1x3x640x640
      - --optShapes=images:8x3x640x640
      - --maxShapes=images:16x3x640x640
    volumes:
      - ./triton/models:/models               
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia                     
              device_ids: ["0"]
              capabilities: [gpu]
    restart: "no"                              

 
  triton:
    image: nvcr.io/nvidia/tritonserver:26.05-py3   
    container_name: triton                     
    command:
      - tritonserver
      - --model-repository=/models
      - --model-control-mode=poll
      - --repository-poll-secs=5
    ports:
      - "8000:8000"                                
      - "8001:8001"                              
      - "8002:8002"                         
    volumes:
      - ./triton/models:/models                 
    shm_size: "1gb"                            
    depends_on:
      trt-builder:
        condition: service_completed_successfully 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]                 
              capabilities: [gpu]
    restart: unless-stopped

  
  prometheus:
    image: prom/prometheus:latest              
    container_name: prometheus
    ports:
      - "9090:9090"                              
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml 
    depends_on:
      - triton                                     
    restart: unless-stopped

  
  grafana:
    image: grafana/grafana:latest                 
    container_name: grafana
    ports:
      - "3000:3000"                                
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin           
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning  
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards  # сами json-дашборды
    depends_on:
      - prometheus                                 # источник данных должен быть готов
    restart: unless-stopped
